### ISSUE TITLE
feat([github acitons]): Reuse cached install even if package version (and nothing else) changed

### ISSUE THREAD

**Issue by shanebdavis** [chill-viking/npm-ci#72]
### Description

Is it possible to ignore the package version when considering whether or not to use the cached "npm ci"? If I do a "npm version patch" and push, it currently invalidates the cache install and reinstalls everything from scratch - except nothing has changed of course.

I need to bump my version for every deploy, so this makes this tool much less effective than it could be.

### Why do we need it? 🤔

90% of the time this tool fails to effectively cache the build. It mostly rebuilds even when not needed.

### Proposed Solution 💡

Maybe it's as easy as running this at the beginning:

```
jq 'del(.version)' package-lock.json | jq 'to_entries | sort_by(.key) | from_entries | .dependencies |= (if type == "object" then to_entries | sort_by(.key) | from_entries else . end)' > normalized-package-lock.json
```

And then using `normalized-package-lock.json` for the cache-key test?

### Additional Context 📝

# Example 1
If I alter CHANGELOG.md and push: **cache gets used - YAY!**
<img width="1006" alt="image" src="https://github.com/user-attachments/assets/03e1fcd7-0c41-4858-af5c-16d900031951">

# Example 2

If I run:

```shell
npm version patch
git push
```

**cache gets ignored (sad!)**

<img width="1004" alt="image" src="https://github.com/user-attachments/assets/5879b159-92a4-43f5-a27b-71f55a2bd54e">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shanebdavis** [comment]
And thanks for this tool! It's exactly what I wanted and dropped in so easily into my CI actions. This one little tweak will make it even better!

**Comment by peterjokumsen** [comment]
Hi @shanebdavis, apologies for not responding until now. Glad you have found this useful.

That's a really cool idea! Will play around with it and hopefully get the change in shortly.
